swagger: "2.0"
info:
   title: Bank Argent API documentation
   description: Contains all available API endpoints in this codebase
   version: "1.0.0"
   termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
   /user/transaction:
      get:
         security:
            - Bearer: []
         tags:
            - User Module
         summary: Get current month transactions
         description: API for getting current month transactions
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
         produces:
            - application/json
         responses:
            "200":
               description: Transaction list successfully retrieved
               schema:
                  $ref: "#/definitions/TransactionListResponse"
            "401":
               description: Unauthorized
            "404":
               description: Not Found
            "500":
               description: Internal Server Error
   /user/transaction/:transactionId:
      get:
         security:
            - Bearer: []
         tags:
            - User Module
         summary: Get a single choosen transaction
         description: API for getting a single choosen transaction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: query
              name: transaction id
              type: string
              description: id of wanted transaction
              required: true
         produces:
            - application/json
         responses:
            "200":
               description: Transaction data successfully retrieved
               schema:
                  $ref: "#/definitions/TransactionResponse"
            "401":
               description: Unauthorized
            "404":
               description: Not Found
            "500":
               description: Internal Server Error
      put:
         security:
            - Bearer: []
         tags:
            - User Module
         summary: modify a single choosen transaction
         description: API for modifying a single choosen transction
         parameters:
            - in: header
              name: Authorization
              type: string
              description: Attach Bearer JWT token
              required: true
            - in: query
              name: transaction id
              type: string
              description: id of wanted transaction
              required: true
            - in: body
              name: body
              description: id of wanted transaction
              required: true
              schema:
                 $ref: "#/definitions/Transaction"
         produces:
            - application/json
         responses:
            "200":
               description: Transaction data successfully updated
               schema:
                  $ref: "#/definitions/ApiResponse"
            "400":
               description: Invalid Fields
            "404":
               description: Not Found
            "500":
               description: Internal Server Error
securityDefinitions:
   Bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
   ApiResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               id:
                  type: string
               email:
                  type: string
   TransactionListResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               data:
                  type: array
                  items:
                     type: object
                     properties:
                        date:
                           type: object
                           description: date of the transaction
                        amount:
                           type: number
                           description: transaction amount
                        balance:
                           type: number
                           description: account balance after transaction
                        transactionType:
                           type: string
                           description: type of the transaction
                        category:
                           type: string
                        notes:
                           type: string
   TransactionResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               date:
                  type: object
                  description: date of the transaction
               amount:
                  type: number
                  description: transaction amount
               balance:
                  type: number
                  description: account balance after transaction
               transactionType:
                  type: string
                  description: type of the transaction
               category:
                  type: string
               notes:
                  type: string
   Transaction:
      type: object
      properties:
         date:
            type: object
            description: date of the transaction
         amount:
            type: number
            description: transaction amount
         balance:
            type: number
            description: account balance after transaction
         transactionType:
            type: string
            description: type of the transaction
         category:
            type: string
            description: category of the transaction
         notes:
            type: string
            description: notes about the transaction
